<code class="language-yum hljs http">language: node_js
node_js: 4
 
# S: Build Lifecycle
install:
  - npm install
 
#before_script:
 # - npm install -g gulp
 
script:
  - hexo g
 
after_script:
  - cd ./public
  - git init
  - git config user.name "lzhr"
  - git config user.email "lzhrsmile@gmail.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle
 
branches:
  only:
    - blog-source
env:
 global:
   - GH_REF: github.com/lzhr/lzhr.github.io.git</code>
